---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consumer-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer-data
  template:
    metadata:
      labels:
        app: consumer-data
    spec:
      containers:
        - name: consumer
#          image: registry.gitlab.sdu.dk/jah/bigdatarepo/interactive:latest
          image: jonfjakobsen/consumer-image:latest
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: consumer-data-storage
              mountPath: /root/code
      volumes:
        - name: consumer-data-storage
          persistentVolumeClaim:
            claimName: consumer-data-pvc