---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fetch-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fetch-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fetch-data
  template:
    metadata:
      labels:
        app: fetch-data
    spec:
      containers:
        - name: producer-data
#          image: registry.gitlab.sdu.dk/jah/bigdatarepo/interactive:latest
          image: ghcr.io/sdu-se-big-data-e24/ingest:latest
          imagePullPolicy: Always
          command: ["sleep", "infinity"]
          volumeMounts:
            - name: producer-data-storage
              mountPath: /root/code
      volumes:
        - name: producer-data-storage
          persistentVolumeClaim:
            claimName: producer-data-pvc