apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: namenode
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  serviceName: "namenode"
  replicas: 1
  selector:
    matchLabels:
      app: namenode
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
          ports:
            - containerPort: 9870
            - containerPort: 9000
          env:
            - name: CLUSTER_NAME
              value: "test"
          envFrom:
            - configMapRef:
                name: hadoop-config
          volumeMounts:
            - name: hadoop-namenode-storage
              mountPath: /hadoop/dfs/name
  volumeClaimTemplates:
    - metadata:
        name: hadoop-namenode-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: namenode
spec:
  selector:
    app: namenode
  ports:
    - name: web
      protocol: TCP
      port: 9870
      targetPort: 9870
    - name: rpc
      protocol: TCP
      port: 9000
      targetPort: 9000
