name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  ConsumptionIndustry:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          context: ./producers
          dockerfile: ./producers/ConsumptionIndustry/Dockerfile
          image_name: ${{ github.repository }}-ConsumptionIndustry  # Add a specific name for the producers
          github_token: ${{ secrets.GITHUB_TOKEN }}

  ProductionConsumptionSettlement:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          context: ./producers
          dockerfile: ./producers/ProductionConsumptionSettlement/Dockerfile
          image_name: ${{ github.repository }}-ProductionConsumptionSettlement  # Add a specific name for the producers
          github_token: ${{ secrets.GITHUB_TOKEN }}