name: Build Docker Image

on:
  push:
    branches:
      - main

jobs:
  producer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker
        uses: docker/setup-buildx-action@v2

      - name: Build and publish a Docker image for ${{ github.repository }}
        uses: macbre/push-to-ghcr@master
        with:
          context: /producer
          image_name: ${{ github.repository }}-producer  # Add a specific name for the producer
          github_token: ${{ secrets.GITHUB_TOKEN }}
#  consumer:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Setup Docker
#        uses: docker/setup-buildx-action@v2
#
#      - name: Build and publish a Docker image for ${{ github.repository }}
#        uses: macbre/push-to-ghcr@master
#        with:
#          image_name: ${{ github.repository }}  # it will be lowercased internally
#          github_token: ${{ secrets.GITHUB_TOKEN }}